export const memberDetails = {
    1: {
        name: "Victor",
        role: "UI UX Team Lead",
        reporting: { name: "Batosh", designation: "CEO", ratings: 4, profile: "https://randomuser.me/api/portraits/men/99.jpg" },
        profile: "https://randomuser.me/api/portraits/men/2.jpg",
        tasks: { completed: 40, incomplete: 10, overdue: 5 },
        currentTasks: [{ title: "Wireframe Design", id: "UX-01", priority: "High" }],
        completedTasks: [{ title: "Prototype", id: "UX-02", priority: "Medium" }],
        failedTasks: [{ title: "UI Review", id: "UX-03", priority: "Low" }],
    },
    2: {
        name: "Alexa",
        role: "Sr. UI UX Designer",
        reporting: { name: "Wincy", designation: "CTO", ratings: 5, profile: "https://randomuser.me/api/portraits/women/3.jpg" },
        profile: "https://randomuser.me/api/portraits/women/3.jpg",
        tasks: { completed: 55, incomplete: 30, overdue: 15 },
        currentTasks: [
            { title: "ZEN Roadmap", id: "ZEN-01", priority: "High" },
            { title: "Test Hub", id: "ZEN-02", priority: "High" },
        ],
        completedTasks: [{ title: "Boards backlog", id: "ZEN-03", priority: "Low" }],
        failedTasks: [{ title: "Backlog", id: "ZEN-04", priority: "Medium" }],
    },
    3: {
        name: "Juliet",
        role: "Blockchain Dev. Team Lead",
        reporting: { name: "Batosh", designation: "CEO", ratings: 4, profile: "https://randomuser.me/api/portraits/women/8.jpg" },
        profile: "https://randomuser.me/api/portraits/men/2.jpg",
        tasks: { completed: 40, incomplete: 10, overdue: 5 },
        currentTasks: [{ title: "Wireframe Design", id: "UX-01", priority: "High" }],
        completedTasks: [{ title: "Prototype", id: "UX-02", priority: "Medium" }],
        failedTasks: [{ title: "UI Review", id: "UX-03", priority: "Low" }],
    },
    4: {
        name: "Hina",
        role: "QA Team Lead",
        reporting: { name: "Wincy", designation: "CTO", ratings: 5, profile: "https://randomuser.me/api/portraits/women/33.jpg" },
        profile: "https://randomuser.me/api/portraits/women/3.jpg",
        tasks: { completed: 55, incomplete: 30, overdue: 15 },
        currentTasks: [
            { title: "ZEN Roadmap", id: "ZEN-01", priority: "High" },
            { title: "Test Hub", id: "ZEN-02", priority: "High" },
        ],
        completedTasks: [{ title: "Boards backlog", id: "ZEN-03", priority: "Low" }],
        failedTasks: [{ title: "Backlog", id: "ZEN-04", priority: "Medium" }],
    },
    5: {
        name: "Steve",
        role: "Ui Ux Team Manager",
        reporting: { name: "Batosh", designation: "CEO", ratings: 4, profile: "https://randomuser.me/api/portraits/men/13.jpg" },
        profile: "https://randomuser.me/api/portraits/men/13.jpg",
        tasks: { completed: 40, incomplete: 10, overdue: 5 },
        currentTasks: [{ title: "Wireframe Design", id: "UX-01", priority: "High" }],
        completedTasks: [{ title: "Prototype", id: "UX-02", priority: "Medium" }],
        failedTasks: [{ title: "UI Review", id: "UX-03", priority: "Low" }],
    },
    6: {
        name: "Andrielle",
        role: "Sr. UI UX Designer",
        reporting: { name: "Wincy", designation: "CTO", ratings: 5, profile: "https://randomuser.me/api/portraits/women/44.jpg" },
        profile: "https://randomuser.me/api/portraits/women/44.jpg",
        tasks: { completed: 55, incomplete: 30, overdue: 15 },
        currentTasks: [
            { title: "ZEN Roadmap", id: "ZEN-01", priority: "High" },
            { title: "Test Hub", id: "ZEN-02", priority: "High" },
        ],
        completedTasks: [{ title: "Boards backlog", id: "ZEN-03", priority: "Low" }],
        failedTasks: [{ title: "Backlog", id: "ZEN-04", priority: "Medium" }],
    },
    7: {
        name: "Billie",
        role: "Blockchain Dev. Team Manager",
        reporting: { name: "Batosh", designation: "CEO", ratings: 4, profile: "https://randomuser.me/api/portraits/men/22.jpg" },
        profile: "https://randomuser.me/api/portraits/men/22.jpg",
        tasks: { completed: 40, incomplete: 10, overdue: 5 },
        currentTasks: [{ title: "Wireframe Design", id: "UX-01", priority: "High" }],
        completedTasks: [{ title: "Prototype", id: "UX-02", priority: "Medium" }],
        failedTasks: [{ title: "UI Review", id: "UX-03", priority: "Low" }],
    },
    8: {
        name: "Alita",
        role: "QA Team Manager",
        reporting: { name: "Wincy", designation: "CTO", ratings: 5, profile: "https://randomuser.me/api/portraits/women/12.jpg" },
        profile: "https://randomuser.me/api/portraits/women/12.jpg",
        tasks: { completed: 55, incomplete: 30, overdue: 15 },
        currentTasks: [
            { title: "ZEN Roadmap", id: "ZEN-01", priority: "High" },
            { title: "Test Hub", id: "ZEN-02", priority: "High" },
        ],
        completedTasks: [{ title: "Boards backlog", id: "ZEN-03", priority: "Low" }],
        failedTasks: [{ title: "Backlog", id: "ZEN-04", priority: "Medium" }],
    },
};

export const membersList = [
    { id: 1, name: "Victor", role: "Ui Ux Team Lead", img: "https://randomuser.me/api/portraits/men/2.jpg", status: "online" },
    { id: 2, name: "Alexa", role: "Sr. Ui Ux Designer", img: "https://randomuser.me/api/portraits/women/3.jpg", status: "online" },
    { id: 3, name: "Juliet", role: "Blockchain Dev. Team Lead", img: "https://randomuser.me/api/portraits/women/8.jpg", status: "offline" },
    { id: 4, name: "Hina", role: "QA Team Lead", img: "https://randomuser.me/api/portraits/women/33.jpg", status: "offline" },
    { id: 5, name: "Steve", role: "Ui Ux Team Manager", img: "https://randomuser.me/api/portraits/men/13.jpg", status: "offline" },
    { id: 6, name: "Andrielle", role: "Sr. Ui Ux Designer", img: "https://randomuser.me/api/portraits/women/44.jpg", status: "online" },
    { id: 7, name: "Billie", role: "Blockchain Dev. Team Manager", img: "https://randomuser.me/api/portraits/men/22.jpg", status: "online" },
    { id: 8, name: "Alita", role: "QA Team Manager", img: "https://randomuser.me/api/portraits/women/12.jpg", status: "offline" },
];
